import { reactive } from "vue";

const state = reactive({
  navItems: [
    {
      root: "/artisans",
      to: "/artisans",
      icon: "eva-globe-outline",
    },
    {
      root: "/profile",
      to: "/profile",
      icon: "eva-square",
    },
  ],
  usePageTransition: false,
  theme: "bright-background",
  textColor: "", // Default text color
  textColorOptions: {
    "bright-background": ["black", "green"],
    "dark-background": ["white", "green"],
  },
  craftOptions: [
    { value: "Plumber", label: "Plumber" },
    { value: "Electrician", label: "Electrician" },
    { value: "Chef", label: "Chef" },
    { value: "Janitor", label: "Janitor" },
    { label: "Farm Work", value: "Farm Work" },
    { label: "Crafts & Handmade", value: "Crafts_Handmade" },
    { label: "Builder", value: "Builder" },
    { label: "Shop Attendant", value: "Shop Attendant" },
    { label: "Mechanic", value: "Mechanic" },
    { label: "Cleaner", value: "Cleaner" },
    { label: "Helper", value: "Helper" },
    { label: "Painter", value: "Painter" },
    { label: "Gym Staff", value: "Gym Staff" },
    { label: "Trainer", value: "Trainer" },
  ],
  locations: [
    {
      id: 1,
      name: "Mombasa",
      constituencies: [
        "Changamwe",
        "Kisauni",
        "Likoni",
        "Jomvu",
        "Nyali",
        "Mvita",
      ],
    },
    {
      id: 30,
      name: "Baringo",
      constituencies: [
        "Baringo Central",
        "Baringo North",
        "Mogotio",
        "Tiaty",
        "Eldama Ravine",
        "Baringo South",
      ],
    },
    {
      id: 36,
      name: "Bomet",
      constituencies: [
        "Bomet East",
        "Bomet Central",
        "Chepalungu",
        "Sotik",
        "Konoin",
      ],
    },

    {
      id: 39,
      name: "Bungoma",
      constituencies: [
        "Bumula",
        "Kabuchai",
        "Kanduyi",
        "Kimilili",
        "Mt. Elgon",
        "Sirisia",
        "Tongaren",
        "Webuye East",
        "Webuye West",
      ],
    },
    {
      id: 40,
      name: "Busia",
      constituencies: [
        "Budalang'i",
        "Butula",
        "Funyula",
        "Matayos",
        "Idokho",
        "Nambale",
        "Teso North",
        "Teso South",
        "Bujwane",
        "Bukoma",
        "Bunyala",
        "Nangina",
        "Bukhungu",
        "Debani",
        "mbuvu",
        "Bukhwamba",
        "Kholokhongo",
        "Makhoma",
        "Namabusi",
        "Nyapera",
      ],
    },
    {
      id: 28,
      name: "Elgeyo-Marakwet",
      constituencies: [
        "Keiyo North",
        "Keiyo South",
        "Marakwet East",
        "Marakwet West",
      ],
    },
    {
      id: 14,
      name: "Embu",
      constituencies: ["Manyatta", "Mbeere North", "Mbeere South", "Runyenjes"],
    },
    {
      id: 7,
      name: "Garissa",
      constituencies: [
        "Balambala",
        "Dadaab",
        "Fafi",
        "Garissa Township",
        "Ijara",
        "Lagdera",
      ],
    },
    {
      id: 43,
      name: "Homa Bay",
      constituencies: [
        "Homa Bay Town",
        "Kabondo Kasipul",
        "Karachuonyo",
        "Kasipul",
        "Ndhiwa",
        "Rangwe",
        "Suba North",
        "Suba South",
      ],
    },
    {
      id: 11,
      name: "Isiolo",
      constituencies: ["Isiolo North", "Isiolo South"],
    },
    {
      id: 34,
      name: "Kajiado",
      constituencies: [
        "Kajiado Central",
        "Kajiado East",
        "Kajiado North",
        "Kajiado South",
        "Kajiado West",
      ],
    },
    {
      id: 37,
      name: "Kakamega",
      constituencies: [
        "Butere",
        "Ikolomani",
        "Khwisero",
        "Lugari",
        "Lurambi",
        "Malava",
        "Matungu",
        "Mumias East",
        "Mumias West",
        "Navakholo",
        "Shinyalu",
      ],
    },
    {
      id: 35,
      name: "Kericho",
      constituencies: [
        "Ainamoi",
        "Kapsoit",
        "Chebisom",
        "Kapkugerwet",
        "Belgut",
        "Kapsuser",
        "Chaik",
        "Chemamul",
        "Kabianga",
        "Kaplelartet",
        "Kebeneti",
        "Kiptere",
        "Seretut",
        "Waldai",
        "Bureti",
        "Kipkelion East",
        "Chepseon",
        "Londiani",
        "Kimugul",
        "Kipkelion West",
        "Kunyak",
        "Kamasian",
        "Chilchila",
        "Sigowet-Soin",
        "Kaplelartet",
        "Soliat",
        "Baregeiwet",
        "Kaitui",
        "Kiptugumo",
        "Kapsegut",
        "Chesiche",
        "Kabokyek",
        "Lekwenyi",
        "Kapkara",
        "Kapsorok",
        "Motero",
        "Kamasega",
        "Kongeren",
        "Simbi",
        "Kaplelach",
        "Kipsitet",
        "Kapchebwai",
        "Koitaborut",
        "Kapkormon",
        "Kejiriet",
        "Kaptalamwa",
      ],
    },
    {
      id: 22,
      name: "Kiambu",
      constituencies: [
        "Gatundu North",
        "Gatundu South",
        "Githunguri",
        "Juja",
        "Kalimoni",
        "Witeithie",
        "Murera",
        "Theta",
        "Kabete",
        "Gitaru",
        "Nyathuna",
        "Muguga",
        "Uthiru",
        "Kiambaa",
        "Kiambu",
        "Kikuyu",
        "Sigona",
        "Karai",
        "Kinoo",
        "Nachu",
        "Limuru",
        "Limuru Central",
        "Limuru East",
        "Karabani",
        "Tigoni",
        "Ndeiya",
        "Ngecha",
        "Rironi",
        "Kamirithu",
        "Bibirioni",
        "Lari",
        "Kamburu",
        "Nyanduma",
        "Kinale",
        "Kirenga",
        "Kijabe",
        "Ruiru",
        "Githurai",
        "Mwihoko",
        "Kiuu",
        "Mwiki",
        "Kahawa Wendani",
        "Kahawa Sukari",
        "Gitothua",
        "Gatongora",
        "Biashara",
        "Thika Town",
      ],
    },
    {
      id: 3,
      name: "Kilifi",
      constituencies: [
        "Ganze",
        "Bamba",
        "Jaribuni",
        "Sokoke",
        "Kaloleni",
        "Mariakani",
        "Kayafungo",
        "Kaloleni",
        "Mwana Mwinga",
        "Kilifi North",
        "Magarini",
        "Maarafa",
        "Magarini",
        "Gongoni",
        "Adu",
        "Garashi",
        "Sabaki",
        "Malindi",
        "Jilore",
        "Kakuyuni",
        "Ganda",
        "Malindi Town",
        "Shella",
        "Rabai",
        "Mwawesa",
        "Ruruma",
        "Kambe-Ribe",
        "Kisurutuni",
        "Tezo",
        "Sokoni",
        "Kibarani",
        "Dabaso",
        "Matsangoni",
        "Watamu",
        "Mnarani",
        "Kilifi South",
        "Junju",
        "Mwarakaya",
        "Shimo la Tewa",
        "Chasimba",
        "Mtepeni",
      ],
    },
    {
      id: 20,
      name: "Kirinyaga",
      constituencies: ["Gichugu", "Kirinyaga Central", "Mwea", "Ndia"],
    },
    {
      id: 45,
      name: "Kisii",
      constituencies: [
        "Bobasi",
        "Bomachoge Borabu",
        "Bomachoge Chache",
        "Bonchari",
        "Kitutu Chache North",
        "Kitutu Chache South",
        "Nyaribari Chache",
        "Nyaribari Masaba",
        "South Mugirango",
      ],
    },
    {
      id: 42,
      name: "Kisumu",
      constituencies: [
        "Kisumu East",
        "Kisumu West",
        "Kisumu Central",
        "Nyakach",
        "Nyando",
        "Seme",
      ],
    },
    {
      id: 15,
      name: "Kitui",
      constituencies: [
        "Kitui Central",
        "Kitui East",
        "Kitui Rural",
        "Kitui South",
        "Kitui West",
        "Mwingi Central",
        "Mwingi North",
        "Mwingi West",
      ],
    },
    {
      id: 2,
      name: "Kwale",
      constituencies: [
        "Kinango",
        "Lunga-Lunga",
        "Bwaga Cheti",
        "Mahuruni",
        "Matuga",
        "Msambweni",
        "Chingwede",
        "Shimba Hills",
        "Dundani",
        "Dzirive",
        "Samburu",
        "Dololo",
        "Diani",
        "Funzi",
        "Wasini",
        "Vanga",
        "Ufumbani",
      ],
    },
    {
      id: 31,
      name: "Laikipia",
      constituencies: ["Laikipia East", "Laikipia North", "Laikipia West"],
    },
    {
      id: 5,
      name: "Lamu",
      constituencies: [
        "Lamu East",
        "Faza",
        "Basuba",
        "Kiunga",
        "Lamu West",
        "Shella",
        "Mkomani",
        "Hindi",
        "Mkunubi",
        "Hongwe",
        "Bahari",
        "Witu",
      ],
    },
    {
      id: 16,
      name: "Machakos",
      constituencies: [
        "Kangundo",
        "Kathiani",
        "Machakos Town",
        "Masinga",
        "Matungulu",
        "Mavoko",
        "Mwala",
        "Yatta",
      ],
    },
    {
      id: 17,
      name: "Makueni",
      constituencies: [
        "Emali/Mulala",
        "Kaiti",
        "Kibwezi East",
        "Kibwezi West",
        "Kilome",
        "Makueni",
        "Mbooni",
      ],
    },
    {
      id: 9,
      name: "Mandera",
      constituencies: [
        "Banissa",
        "Lafey",
        "Mandera East",
        "Mandera North",
        "Mandera South",
        "Mandera West",
      ],
    },
    {
      id: 12,
      name: "Meru",
      constituencies: [
        "Buuri",
        "Central Imenti",
        "Igembe Central",
        "Igembe North",
        "Igembe South",
        "North Imenti",
        "South Imenti",
        "Tigania East",
        "Tigania West",
      ],
    },
    {
      id: 44,
      name: "Migori",
      constituencies: [
        "Awendo",
        "Kuria East",
        "Kuria West",
        "Nyatike",
        "Rongo",
        "Suna East",
        "Suna West",
        "Uriri",
      ],
    },
    {
      id: 10,
      name: "Marsabit",
      constituencies: ["Laisamis", "Moyale", "North Horr", "Saku"],
    },
    {
      id: 21,
      name: "Murang'a",
      constituencies: [
        "Gatanga",
        "Kandara",
        "Kangema",
        "Kiharu",
        "Kigumo",
        "Maragua",
        "Mathioya",
      ],
    },
    {
      id: 47,
      name: "Nairobi",
      constituencies: [
        "Dagoretti North",
        "Kilimani",
        "Kawangware",
        "Gatina",
        "Kileleshwa",
        "Kabiro",
        "Riruta",
        "Waithaka",
        "Uthiru",
        "Dagoretti South",
        "Embakasi Central",
        "Kayole",
        "Komarock",
        "Matopeni",
        "Embakasi East",
        "Utawala",
        "Mihango",
        "Embakasi North",
        "Kariobangi North",
        "Dandora Area I",
        "Dandora Area II",
        "Dandora Area III",
        "Dandora Area IV",
        "Embakasi South",
        "Imara Daima",
        "Kware",
        "Kwa Njenga",
        "Kwa Reuben",
        "Pipeline",
        "Embakasi West",
        "Umoja I",
        "Umoja II",
        "Kamukunji",
        "Pumwani",
        "Airbase",
        "California",
        "Eastleigh North",
        "Eastleigh South",
        "Kasarani",
        "Clay City",
        "Mwiki",
        "Kamulu",
        "Njiru",
        "Ruai",
        "Kibra",
        "Laini Saba",
        "Lindi",
        "Makina",
        "Woodley",
        "Sarang'ombe",
        "Lang'ata",
        "Karen",
        "Mugumo-ini",
        "South C",
        "Nyayo",
        "Makadara",
        "Maringo",
        "Hamza",
        "Viwandani",
        "Makongeni",
        "Mbotela",
        "Harambee",
        "Bahati",
        "Mathare",
        "Roysambu",
        "Garden Estate",
        "Ridge Ways",
        "Githurai 44",
        "Kahawa West",
        "Zimmerman",
        "Ruaraka",
        "Babadogo",
        "Utalii",
        "Mathare North",
        "Lucky Summer",
        "Korogocho",
        "Starehe",
        "Pangani",
        "Ziwani",
        "Kariokor",
        "Landimawe",
        "Westlands",
        "Kitisuru",
        "Parklands",
        "Highridge",
        "Karura",
        "Kangemi",
        "Mountain View",
      ],
    },
    {
      id: 32,
      name: "Nakuru",
      constituencies: [
        "Bahati",
        "Gilgil",
        "Kuresoi North",
        "Kuresoi South",
        "Molo",
        "Naivasha",
        "Nakuru Town East",
        "Nakuru Town West",
        "Njoro",
        "Rongai",
        "Subukia",
      ],
    },
    {
      id: 29,
      name: "Nandi",
      constituencies: [
        "Aldai",
        "Chesumei",
        "Emgwen",
        "Mosop",
        "Nandi Hills",
        "Tindiret",
      ],
    },
    {
      id: 33,
      name: "Narok",
      constituencies: [
        "Emurua Dikirr",
        "Kilgoris",
        "Narok East",
        "Narok North",
        "Narok South",
        "Narok West",
      ],
    },
    {
      id: 46,
      name: "Nyamira",
      constituencies: [
        "Borabu",
        "Manga",
        "Masaba North",
        "Nyamira North",
        "West Mugirango",
      ],
    },
    {
      id: 18,
      name: "Nyandarua",
      constituencies: [
        "Kinangop",
        "Kipipiri",
        "Ol Kalou",
        "Ol Jorok",
        "Ndaragua",
      ],
    },
    {
      id: 19,
      name: "Nyeri",
      constituencies: [
        "Tetu",
        "Aguthi-Gaaki",
        "Dedan Kimathi",
        "Wamagana",
        "Othaya",
        "Kanyange",
        "Kianganda",
        "Chinga",
        "Iria-ini",
        "Karima",
        "Mahiga",
        "Mumwe",
        "Thuti",
        "Mukurwe-ini",
        "Gakindu",
        "Giathugu",
        "Rutune",
        "Thanu",
        "Gikondi",
        "Githi",
        "Muhito",
        "Kieni",
        "Mathira",
        "Nyeri Town",
      ],
    },
    {
      id: 41,
      name: "Siaya",
      constituencies: [
        "Ugenya",
        "Ugunja",
        "Alego Usonga",
        "Gem",
        "Bondo",
        "Rarieda",
      ],
    },

    {
      id: 38,
      name: "Vihiga",
      constituencies: ["Vihiga", "Sabatia", "Hamisi", "Luanda", "Emuhaya"],
    },
    {
      id: 27,
      name: "Uasin Gishu",
      constituencies: [
        "Soy",
        "Turbo",
        "Moiben",
        "Ainabkoi",
        "Kapseret",
        "Kesses",
      ],
    },
    {
      id: 26,
      name: "Trans Nzoia",
      constituencies: [
        "Kwanza",
        "Endebess",
        "Saboti",
        "Kiminini",
        "Cherangany",
      ],
    },
    {
      id: 25,
      name: "Samburu",
      constituencies: ["Samburu West", "Samburu East", "Samburu North"],
    },
    {
      id: 24,
      name: "West Pokot",
      constituencies: ["Kapenguria", "Sigor", "Kacheliba", "Pokot South"],
    },
    {
      id: 23,
      name: "Turkana",
      constituencies: [
        "Turkana West",
        "Turkana North",
        "Turkana Central",
        "Turkana East",
        "Turkana South",
        "Loima",
        "Lodwar",
        "Kaalig",
        "Kainuk",
        "Kakuma",
        "Kalokol",
        "Katilu",
        "Kibish",
        "Kerio",
        "Lapur",
        "Lokichar",
        "Lokichogio",
        "Lokitaung",
        "Lokori",
        "Kapedo",
        "Oropol",
        "Turkwel",
      ],
    },
    {
      id: 13,
      name: "Tharaka-Nithi",
      constituencies: ["Maara", "Tharaka", "Chuka"],
    },
    {
      id: 8,
      name: "Wajir",
      constituencies: [
        "Wajir West",
        "Wajir North",
        "Tarbaj",
        "Wajir East",
        "Wajir South",
        "Eldas",
      ],
    },

    {
      id: 4,
      name: "Tana River",
      constituencies: [
        "Garson",
        "Kalole",
        "Bura",
        "Ariti",
        "Borobini",
        "Chiffiri",
        "Maziwa",
        "Wenje",
        "Wema",
        "Ngao",
        "Idsowe",
        "Ijara",
        "Kamwangi",
        "Murarandia",
        "Wacha Kone",
        "Furaha",
        "Fitina",
        "Irangi",
        "Ingile",
        "Idsowe",
        "Handarako",
        "Kipini",
        "Laini",
        "Bohoni",
        "Bongonoko",
        "Chathoro",
        "Baomo",
        "Bangale",
        "Balguda",
        "Chewani",
      ],
    },
    {
      id: 6,
      name: "Taita-Taveta",
      constituencies: [
        "Taveta",
        "Voi",
        "Wundanyi",
        "Mwatate",
        "Loima",
        "Bomeni ",
        "Werugha ",
        "Rong’e ",
        "Mahoo ",
        "Kasighau ",
        "Sagala ",
        "Marungu ",
        "Kaloleni ",
        "Ngolia ",
        "Wusi/Kishamba ",
        "Mbololo ",
        "Chawia ",
        "Bura ",
        "Mwanda ",
        "Mata ",
        "Wundanyi",
        "Wumingu ",
        "Mboghoni ",
        "Chala ",
        "Mwatate ",
      ],
    },
  ],
  artisans: [
    {
      id: 1,
      name: "Jeff Thuo",
      craft: "Janitor",
      location: "Westlands",
      county: "Nairobi",
      email: "",
      phone: "0743238069",
      availabilityStatus: "Available",
      lastJobCompletionDate: "2024-09-01",
      showContact: false,
    },
    {
      id: 2,
      name: "Jerry Juma",
      craft: "Janitor",
      location: "Westlands",
      county: "Nairobi",
      email: "",
      phone: "0707629420",
      availabilityStatus: "Available",
      lastJobCompletionDate: "2024-09-24",
      showContact: false,
    },
    {
      id: 3,
      name: "Elijah Ngari",
      craft: "Electrician",
      location: "Ruiru",
      county: "Kiambu",
      email: "",
      phone: "0791777978",
      availabilityStatus: "Available",
      lastJobCompletionDate: "2024-06-01",
      showContact: false,
    },
    {
      id: 4,
      name: "Kim Kibathi",
      craft: "Plumber",
      location: "Juja",
      county: "Kiambu",
      email: "",
      phone: "0724356177",
      availabilityStatus: "Available",
      lastJobCompletionDate: "2024-09-01",
      showContact: false,
    },
    {
      id: 5,
      name: "Justus Kariuki",
      craft: "Plumber",
      location: "Nyeri Town",
      county: "Nyeri",
      email: "",
      phone: "0757460774",
      availabilityStatus: "Available",
      lastJobCompletionDate: "2024-09-01",
      showContact: false,
    },
    {
      id: 6,
      name: "David Mbugua",
      craft: "Chef",
      location: "Ruiru",
      county: "Kiambu",
      email: "",
      phone: "0703148750",
      availabilityStatus: "Uavailable",
      lastJobCompletionDate: "2024-09-12",
      showContact: false,
    },
    {
      id: 7,
      name: "Samwel Thuo",
      craft: "Plumber",
      location: "Ruiru",
      county: "Kiambu",
      email: "",
      phone: "0707080474",
      availabilityStatus: "Unavailable",
      lastJobCompletionDate: "2024-07-18",
      showContact: false,
    },
    {
      id: 8,
      name: "Denis Mbugua",
      craft: "Helper",
      location: "Machakos Town",
      county: "Machakos",
      email: "",
      phone: "0718214511",
      availabilityStatus: "Available",
      lastJobCompletionDate: "2024-09-07",
      showContact: false,
    },
    {
      id: 9,
      name: "Ephraim Bosire",
      craft: "Helper",
      location: "Juja",
      county: "Kiambu",
      email: "",
      phone: "0791325823",
      availabilityStatus: "Unavailable",
      lastJobCompletionDate: "2024-09-20",
      showContact: false,
    },
    {
      id: 10,
      name: "Boniface Kim",
      craft: "Plumber",
      location: "Juja",
      county: "Kiambu",
      email: "",
      phone: "0794341720",
      availabilityStatus: "Available",
      lastJobCompletionDate: "2024-08-19",
      showContact: false,
    },
    {
      id: 11,
      name: "Ezbon Gichiru",
      craft: "Farm Work",
      location: "Othaya",
      county: "Nyeri",
      email: "",
      phone: "0746204887",
      availabilityStatus: "Available",
      lastJobCompletionDate: "2024-09-18",
      showContact: false,
    },
    {
      id: 12,
      name: "Karol Kosgei",
      craft: "Chef",
      location: "Shimba Hills",
      county: "Kwale",
      email: "",
      phone: "0746204887",
      availabilityStatus: "Available",
      lastJobCompletionDate: "2024-09-10",
      showContact: false,
    },
    {
      id: 13,
      name: "Samuel Kaniu",
      craft: "Shop Attendant",
      location: "Kasarani",
      county: "Nairobi",
      email: "",
      phone: "0791178691",
      availabilityStatus: "Available",
      lastJobCompletionDate: "2024-09-15",
      showContact: false,
    },
  ],
  groups: [
    {
      id: 1,
      name: "Cleaning Group",
      county: "Nairobi",
      location: "Westlands",
      contactPhone: "0712345678",
      members: [
        { id: 1, fullName: "Edwin Mburu", role: "Supervisor" },
        { id: 2, fullName: "Haggai Wainaina", role: "Cleaner" },
        { id: 3, fullName: "Steven Chege", role: "Janitor" },
        { id: 4, fullName: "Nancy Maingi", role: "Cleaner" },
        { id: 5, fullName: "Nelson Mbogo", role: "Cleaner" },
      ],
      availabilityStatus: "Available",
      lastJobCompletionDate: "2024-08-30",
      showContact: false,
    },
    {
      id: 2,
      name: "Builders Cooperative",
      location: "Nyali",
      county: "Mombasa",
      contactPhone: "0759716308",
      members: [
        { fullName: "Eric Mwangi", role: "Builder" },
        { fullName: "David Kennedy", role: "Painter" },
        { fullName: "Simon Kariuki", role: "Painter" },
      ],
      availabilityStatus: "Unavailable",
      lastJobCompletionDate: "2024-09-05",
      showContact: false,
    },
    {
      id: 3,
      name: "Cleaning Crew",
      county: "Kiambu",
      location: "Kahawa Sukari",
      members: [
        { fullName: "Mark Ouma", role: "Cleaner" },
        { fullName: "Lucy Akinyi", role: "Janitor" },
      ],
      location: "Kisauni",
      county: "Mombasa",
      contactPhone: "0711234567",
      availabilityStatus: "Unavailable",
      lastJobCompletionDate: "2024-09-03",
      showContact: false,
    },
  ],
  craftOptions: [
    { value: "Plumber", label: "Plumber" },
    { value: "Electrician", label: "Electrician" },
    { value: "Chef", label: "Chef" },
    { value: "Janitor", label: "Janitor" },
    { label: "Farm Work", value: "Farm Work" },
    { label: "Crafts & Handmade", value: "Crafts_Handmade" },
    { label: "Builder", value: "Builder" },
    { label: "Shop Attendant", value: "Shop Attendant" },
    { label: "Mechanic", value: "Mechanic" },
    { label: "Cleaner", value: "Cleaner" },
    { label: "Helper", value: "Helper" },
    { label: "Painter", value: "Painter" },
    { label: "Gym Staff", value: "Gym Staff" },
    { label: "Trainer", value: "Trainer" },
  ],
  shops: [
    {
      id: 1,
      name: "Tool Shop",
      location: "Westlands",
      county: "Nairobi",
      products: [
        { id: 1, name: "Hammer", price: 500, available: true },
        { id: 2, name: "Wrench", price: 300, available: false },
      ],
      jobs: [
        { id: 1, title: "Sales Assistant", shift: "Morning", available: true },
        { id: 2, title: "Cashier", shift: "Evening", available: false },
      ],
    },
    {
      id: 2,
      name: "Kibanda Shop",
      location: "Ruiru",
      county: "Kiambu",
      products: [
        { id: 1, name: "Ugali", price: 20, available: true },
        { id: 2, name: "Fish", price: 70, available: false },
      ],
      jobs: [
        {
          id: 1,
          title: "Sales Assistant",
          shift: "Afternoon",
          available: true,
        },
        { id: 2, title: "Cashier", shift: "Evening", available: false },
      ],
    },
  ],
});

const store = {
  state,
  setUserDetails(userDetails) {
    state.user.displayName = userDetails.displayName;
    state.user.username = userDetails.username;
    state.user.email = userDetails.email;
    state.user.jobCategory = userDetails.jobCategory;
    state.user.availability = userDetails.availability;
  },
  setLocation(location) {
    state.locations.push(location);
  },
};
export default store;
